### ISSUE TITLE
Added libraries are not shown when coming back to Excalideck later

### ISSUE THREAD

**Issue by pavinduLakshan** [excalideck/excalideck#47]
First off, thanks for building such an amazing tool for creating slides with hand-drawn like designs. I'm using it for designing wireframes for my project.

Recently I'm seeing weird behaviour when adding a library to excalideck. After clicking `add to excalideck`, I'm redirected to excalideck.com and the added library can be accessed once. However, if I come back (reload/close tab and open in new tab etc) to excalideck.com later, I no longer see the added library.

In excalidraw, once I added a library, I can access it every time when I open the app, but I'm not seeing such behaviour with excalideck and it annoys me so much, as I cannot add those great hand-drawn looking icons to my slides.

It will be a great help if you can look into this.  
Thanks in Advance.

**Comment by pscanf** [comment]
Hey @pavinduLakshan , glad you're enjoying the app and thanks for reporting this issue!

Initial question: are you using `excalideck.com` or `app.excalideck.com` ? 

[`excalideck.com`](https://excalideck.com) is the homepage of the project, and it doesn't save anything you do: every time you reload the page you get the "marketing homepage" and an empty libraries list.

[`app.excalideck.com`](https://app.excalideck.com) instead is the "proper" app that  _should_ save both your work and the libraries you add to it (they are saved to `localStorage`).

In case you are indeed using `app.excalideck.com`, some follow-up questions:

1. what browser / operating system are you using? (I tested the behaviour on Chrome, Firefox, and Safari on macOS, and everything appears to be working, but it might be an issue of a particular browser / OS)
1. do you have any extension / browser setting that might block the usage of `localStorage`?
1. is your deck very large? (`localStorage` is limited to 5MB, it probably behaves weirdly when the size is exceeded)

**Comment by pavinduLakshan** [comment]
Ahh, I was not using app.excalideck.com. Now I see. Thanks for replying.
